'use client';

import { Archive, Pencil, Save } from 'lucide-react';
import { ChangeEvent, FormEvent, useState } from 'react';
import { TeamMark } from './AppShell';
import { useFrontendState } from '../lib/frontend-state';
import { useUi } from './UiProvider';
import { useUnsavedChanges } from '../lib/use-unsaved-changes';
import { optimizeImageFile } from '../lib/image-utils';
import { canManageEdition, useFrontendSession } from '../lib/frontend-session';

type TeamBase = { id: string; name: string; initial: string; tone: string; logo: string; athletes: number };
export function TeamManager({ team, readOnly = false }: { team: TeamBase; readOnly?: boolean }) {
  const { state, commit } = useFrontendState(); const { confirm, toast } = useUi(); const { session } = useFrontendSession();
  const override = state.teams[team.id] ?? {}; const current = { name: override.name ?? team.name, initials: override.initials ?? team.initial, responsible: override.responsible ?? '', logo: override.logo ?? team.logo, archived: override.archived ?? false };
  const [editing, setEditing] = useState(false); const [draft, setDraft] = useState(current); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('');
  const dirty = JSON.stringify(draft) !== JSON.stringify(current); const allowed = canManageEdition(session);
  useUnsavedChanges(editing && dirty && !submitting);
  async function chooseLogo(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (file.size > 8 * 1024 * 1024) { setError('A imagem deve ter no máximo 8 MB.'); return; } try { const logo = await optimizeImageFile(file); setDraft((value) => ({ ...value, logo })); setError(''); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível processar a imagem.'); } }
  function save(event: FormEvent) { event.preventDefault(); if (submitting || !dirty) return; if (draft.name.trim().length < 2 || draft.initials.trim().length < 2) { setError('Informe nome e sigla válidos.'); return; } setSubmitting(true); const saved = commit((value) => ({ ...value, teams: { ...value.teams, [team.id]: { ...value.teams[team.id], ...draft, name: draft.name.trim(), initials: draft.initials.trim().toUpperCase() } } }), { action: 'Equipe alterada', entity: current.name, before: current.name, after: draft.name }); setSubmitting(false); if (saved) setEditing(false); }
  async function toggleArchive() { const archived = !current.archived; if (archived && !(await confirm({ title: 'Arquivar equipe?', message: 'Ela deixará de aparecer nos novos cadastros, mas o histórico e os resultados serão preservados.', confirmLabel: 'Arquivar', danger: true }))) return; commit((value) => ({ ...value, teams: { ...value.teams, [team.id]: { ...value.teams[team.id], archived } } }), { action: archived ? 'Equipe arquivada' : 'Equipe restaurada', entity: current.name, after: archived ? 'Arquivada' : 'Ativa' }); if (!archived) toast('Equipe restaurada.', 'success'); }
  return <><section className={`team-hero team-detail-heading${current.archived ? ' is-archived' : ''}`}><TeamMark initial={current.initials[0] ?? team.initial} tone={team.tone} logo={current.logo} /><div><h2>{current.name}</h2><p>{current.archived ? 'Equipe arquivada' : `${override.athletes ?? team.athletes} atletas cadastrados na edição`}</p></div></section>{!readOnly && allowed && editing ? <form className="entity-form inline-management-form form-step-enter" onSubmit={save} noValidate><label><span>Nome da equipe</span><input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} required /></label><label><span>Sigla</span><input value={draft.initials} onChange={(event) => setDraft({ ...draft, initials: event.target.value })} required minLength={2} maxLength={8} /></label><label><span>Responsável</span><input value={draft.responsible} onChange={(event) => setDraft({ ...draft, responsible: event.target.value })} placeholder="Nome do responsável" /></label><label><span>Logotipo</span><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={chooseLogo} /></label><small className="field-help">A imagem é reduzida e convertida para WebP antes de ser armazenada.</small>{error ? <p className="form-error" role="alert">{error}</p> : null}<div className="form-actions"><button type="button" className="secondary-button" onClick={() => { setDraft(current); setEditing(false); }}>Cancelar</button><button type="submit" className="primary-button" disabled={!dirty || submitting}><Save size={17} /> {submitting ? 'Salvando…' : 'Salvar'}</button></div></form> : !readOnly && allowed ? <div className="form-actions team-management-actions"><button type="button" className="secondary-button" onClick={toggleArchive}><Archive size={17} /> {current.archived ? 'Restaurar' : 'Arquivar'}</button><button type="button" className="primary-button" onClick={() => { setDraft(current); setEditing(true); }}><Pencil size={17} /> Editar equipe</button></div> : null}</>;
}
