'use client';

import Link from 'next/link';
import { ChevronDown, Plus, Save, UserRound, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { EmptyState } from './AppShell';
import { useFrontendState } from '../lib/repositories/browser-repository';
import { canManageDiscipline, canManageEdition, useFrontendSession } from '../lib/frontend-session';

type ExistingAthlete = { id: string; name: string; modalities: readonly string[] };
type ManagedAthlete = { id: string; name: string; modalities: string[]; created: boolean };
const tones = ['blue', 'pink', 'orange'] as const;

export function TeamRosterManager({ teamId, existingAthletes, disciplines, readOnly = false }: { teamId: string; existingAthletes: ExistingAthlete[]; disciplines: string[]; readOnly?: boolean }) {
  const [editingId, setEditingId] = useState<string | null>(null); const [selection, setSelection] = useState<string[]>([]); const [submitting, setSubmitting] = useState(false);
  const { state, commit } = useFrontendState(); const { session } = useFrontendSession();
  const athletes = useMemo<ManagedAthlete[]>(() => { const seeded = existingAthletes.map((athlete) => ({ id: athlete.id, name: state.athletes[athlete.id]?.name ?? athlete.name, modalities: state.athletes[athlete.id]?.modalities ?? [...athlete.modalities], created: false })); const seedIds = new Set(seeded.map((athlete) => athlete.id)); const created = Object.entries(state.athletes).filter(([id, athlete]) => !seedIds.has(id) && athlete.created && athlete.teamId === teamId).map(([id, athlete]) => ({ id, name: athlete.name ?? 'Atleta', modalities: athlete.modalities ?? [], created: true })); return [...seeded, ...created]; }, [existingAthletes, state.athletes, teamId]);
  const groups = [...disciplines.filter((discipline) => athletes.some((athlete) => athlete.modalities.includes(discipline))).map((name) => ({ name, athletes: athletes.filter((athlete) => athlete.modalities.includes(name)) })), ...(athletes.some((athlete) => !athlete.modalities.length) ? [{ name: 'Sem modalidade', athletes: athletes.filter((athlete) => !athlete.modalities.length) }] : [])];
  const canEditAny = canManageEdition(session) || disciplines.some((discipline) => canManageDiscipline(session, discipline));
  function startAssociation(athlete: ManagedAthlete) { setEditingId(athlete.id); setSelection(athlete.modalities); }
  function toggle(discipline: string) { if (!canManageDiscipline(session, discipline)) return; setSelection((current) => current.includes(discipline) ? current.filter((item) => item !== discipline) : [...current, discipline]); }
  function saveAssociation(id: string) { if (submitting) return; setSubmitting(true); const athlete = athletes.find((item) => item.id === id); const saved = commit((current) => ({ ...current, athletes: { ...current.athletes, [id]: { ...current.athletes[id], name: athlete?.name, teamId, modalities: selection, created: current.athletes[id]?.created ?? athlete?.created } } }), { action: 'Modalidades do atleta alteradas', entity: athlete?.name ?? id, before: athlete?.modalities.join(', ') || 'Sem modalidade', after: selection.join(', ') || 'Sem modalidade' }); setSubmitting(false); if (saved) setEditingId(null); }
  function renderAthlete(athlete: ManagedAthlete) { return <article className="roster-manage-row" key={athlete.id}><span className="jersey-number"><UserRound size={16} /></span><span className="roster-athlete-copy">{readOnly ? <strong>{athlete.name}</strong> : <Link href={`/athletes/${athlete.id}`}><strong>{athlete.name}</strong></Link>}<small>{athlete.created && !readOnly ? 'Cadastro desta edição' : 'Atleta da equipe'}</small></span>{!readOnly && canEditAny ? <button type="button" className="roster-associate-button" onClick={() => editingId === athlete.id ? setEditingId(null) : startAssociation(athlete)} aria-label={`Editar modalidades de ${athlete.name}`} aria-expanded={editingId === athlete.id}><Plus size={17} /></button> : null}{editingId === athlete.id && !readOnly ? <div className="local-athlete-editor form-step-enter"><div>{disciplines.map((discipline) => <label key={discipline} className={!canManageDiscipline(session, discipline) ? 'is-disabled' : ''}><input type="checkbox" checked={selection.includes(discipline)} onChange={() => toggle(discipline)} disabled={!canManageDiscipline(session, discipline)} /><span>{discipline}</span></label>)}</div><div className="local-athlete-editor-actions"><button type="button" onClick={() => setEditingId(null)}><X size={16} />Cancelar</button><button type="button" onClick={() => saveAssociation(athlete.id)} disabled={submitting}><Save size={16} />{submitting ? 'Salvando…' : 'Salvar'}</button></div></div> : null}</article>; }
  if (!athletes.length) return <EmptyState title="SEM ATLETAS" copy={readOnly ? 'Esta equipe ainda não possui elenco publicado.' : 'Cadastre o primeiro atleta desta equipe pelo botão superior.'} />;
  return <div className="team-modality-list">{groups.map((group, index) => { const tone = tones[index % tones.length]; return <details className={`team-modality team-modality-${tone}`} key={group.name} open={index === 0}><summary><span className={`team-modality-mark mark-${tone}`}>{String(index + 1).padStart(2, '0')}</span><span className="team-modality-copy"><strong>{group.name}</strong><small>{group.athletes.length} atletas</small></span><ChevronDown size={21} aria-hidden="true" /></summary><div className="team-modality-roster"><div className="stack-list">{group.athletes.map(renderAthlete)}</div></div></details>; })}</div>;
}
